# Phần đầu giữ nguyên

commands:
  # Các lệnh khác giữ nguyên

  feed:
    description: Làm đầy thanh đói cho bản thân hoặc người chơi khác
    usage: /<command> [player|all]
    aliases: [eat]

permissions:
  # Các quyền khác giữ nguyên

  acupracticecore.cmd.feed:
    description: Cho phép người chơi sử dụng lệnh feed để làm đầy thanh đói của bản thân
    default: op
  acupracticecore.cmd.feed.others:
    description: Cho phép người chơi feed người chơi khác
    default: op
  acupracticecore.cmd.feed.all:
    description: Cho phép người chơi feed tất cả người chơi trên server
    default: op